url: http://kirbyt.github.io
baseurl: /timeline-jekyll-theme

# Site Settings
title: Mehdi Mirza
description: ""
keywords: "My personal page"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
